import type { DemandRecord } from "@/types/demo";

export const SEEDED_DEMAND: DemandRecord[] = [
  {
    id: "seed-001",
    timestamp: "2026-06-05T08:35:00Z",
    query: "Need wedding guest outfit for an outdoor ceremony this weekend, men's size 42 under $400",
    inputMode: "text",
    mode: "demo",
    occasion: "outdoor wedding",
    requestedItems: ["outfit", "shirt", "trousers", "shoes"],
    gender: "Men",
    size: "42",
    budget: 400,
    constraints: ["outdoor", "under budget"],
    foundRelevantMatch: true,
    foundInStock: true,
    selectedProductIds: ["27152", "18197", "45595"],
    missedReason: null,
    estimatedLostRevenue: 0,
    store: "RetailNext Oak Street",
    category: "mens occasionwear",
    demandQualityScore: 92,
    source: "Seeded demand signal",
  },
  {
    id: "seed-002",
    timestamp: "2026-06-05T08:50:00Z",
    query: "plus-size formal dress for winter wedding under $250",
    inputMode: "text",
    mode: "demo",
    occasion: "winter wedding",
    requestedItems: ["formalwear", "dress"],
    gender: "Women",
    size: "18",
    budget: 250,
    constraints: ["plus-size", "formal"],
    foundRelevantMatch: false,
    foundInStock: false,
    selectedProductIds: [],
    missedReason: "Unmet demand: plus-size formalwear is not available in requested size at RetailNext Oak Street.",
    estimatedLostRevenue: 250,
    store: "RetailNext Oak Street",
    category: "women formalwear",
    demandQualityScore: 94,
    source: "Seeded demand signal",
  },
  {
    id: "seed-003",
    timestamp: "2026-06-05T09:05:00Z",
    query: "work gala black dress women size 10",
    inputMode: "text",
    mode: "demo",
    occasion: "work gala",
    requestedItems: ["dress", "shoes"],
    gender: "Women",
    size: "10",
    budget: 300,
    constraints: ["formal", "evening"],
    foundRelevantMatch: true,
    foundInStock: true,
    selectedProductIds: ["48481", "59982"],
    missedReason: null,
    estimatedLostRevenue: 0,
    store: "RetailNext Oak Street",
    category: "women occasionwear",
    demandQualityScore: 89,
    source: "Seeded demand signal",
  },
  {
    id: "seed-004",
    timestamp: "2026-06-05T09:25:00Z",
    query: "graduation shoes and bag this weekend",
    inputMode: "text",
    mode: "demo",
    occasion: "graduation",
    requestedItems: ["shoes", "bag", "accessories"],
    gender: "Women",
    size: "8",
    budget: 220,
    constraints: ["comfortable"],
    foundRelevantMatch: true,
    foundInStock: true,
    selectedProductIds: ["10616", "32379"],
    missedReason: "Partial miss: bag request could not be fulfilled from the cookbook-backed local range.",
    estimatedLostRevenue: 80,
    store: "RetailNext Oak Street",
    category: "ceremony accessories",
    demandQualityScore: 84,
    source: "Seeded demand signal",
  },
  {
    id: "seed-005",
    timestamp: "2026-06-05T09:40:00Z",
    query: "review: website says occasion dress available but customer cannot find it",
    inputMode: "text",
    mode: "demo",
    occasion: "findability issue",
    requestedItems: ["dress"],
    gender: "Women",
    size: "12",
    budget: null,
    constraints: ["store findability"],
    foundRelevantMatch: true,
    foundInStock: true,
    selectedProductIds: ["59973"],
    missedReason: "Store findability issue: customer needed associate help to locate product.",
    estimatedLostRevenue: 0,
    store: "RetailNext Oak Street",
    category: "women occasionwear",
    demandQualityScore: 77,
    source: "Seeded review signal",
  },
];
