import type { StoreLocationRecord } from "@/types/demo";

export const STORE_LOCATIONS: StoreLocationRecord[] = [
  {
    productId: "27152",
    storeId: "oak-street",
    floor: "Floor 2",
    department: "Menswear",
    zone: "Occasionwear",
    aisle: "Aisle 12",
    bay: "Bay 4",
    landmark: "new-season rail near fitting rooms",
    associateNote: "Pair with navy trouser rail and brown formal shoes for outdoor wedding requests.",
    routeSteps: [
      "Enter through the main entrance on Ground Floor",
      "Take the escalator to Floor 2",
      "Turn right into Menswear",
      "Go to Aisle 12",
      "Item is on Bay 4, new-season rail",
      "Associate can prepare Fitting Room 3",
    ],
  },
  {
    productId: "18197",
    storeId: "oak-street",
    floor: "Floor 2",
    department: "Menswear",
    zone: "Tailoring",
    aisle: "Aisle 13",
    bay: "Bay 2",
    landmark: "navy trouser wall beside alterations desk",
    associateNote: "Check waist 34 and 36 first; size 42 is held in back stock.",
    routeSteps: [
      "Enter through the main entrance on Ground Floor",
      "Take the escalator to Floor 2",
      "Turn right into Menswear",
      "Continue to Tailoring",
      "Go to Aisle 13, Bay 2",
      "Associate can prepare Fitting Room 3",
    ],
  },
  {
    productId: "14713",
    storeId: "oak-street",
    floor: "Floor 2",
    department: "Menswear",
    zone: "Tailoring",
    aisle: "Aisle 13",
    bay: "Bay 4",
    landmark: "brown tailored trouser rail beside navy separates",
    associateNote: "Use as the outdoor wedding trouser when navy sizes are constrained.",
    routeSteps: [
      "Enter through the main entrance on Ground Floor",
      "Take the escalator to Floor 2",
      "Turn right into Menswear",
      "Continue to Tailoring",
      "Go to Aisle 13, Bay 4",
      "Associate can prepare Fitting Room 3",
    ],
  },
  {
    productId: "45595",
    storeId: "oak-street",
    floor: "Floor 1",
    department: "Men's Shoes",
    zone: "Formal Footwear",
    aisle: "Aisle 7",
    bay: "Bay 5",
    landmark: "brown leather display below occasionwear signage",
    associateNote: "Bring shoe horn and weather-protect spray for outdoor events.",
    routeSteps: [
      "Enter through the main entrance on Ground Floor",
      "Walk past Beauty to the central escalator",
      "Stop at Floor 1 Men's Shoes",
      "Turn left into Formal Footwear",
      "Go to Aisle 7, Bay 5",
      "Associate can prepare Fitting Room 3",
    ],
  },
  {
    productId: "49696",
    storeId: "oak-street",
    floor: "Floor 2",
    department: "Menswear",
    zone: "Accessories",
    aisle: "Aisle 12",
    bay: "Bay 1",
    landmark: "tie wall beside the occasionwear rail",
    associateNote: "Use this as the final accent for navy wedding and interview looks.",
    routeSteps: [
      "Enter through the main entrance on Ground Floor",
      "Take the escalator to Floor 2",
      "Turn right into Menswear",
      "Stop at Accessories",
      "Go to Aisle 12, Bay 1",
      "Associate can prepare Fitting Room 3",
    ],
  },
  {
    productId: "16035",
    storeId: "oak-street",
    floor: "Floor 2",
    department: "Menswear",
    zone: "Shirting",
    aisle: "Aisle 10",
    bay: "Bay 3",
    landmark: "white shirt wall beside tailoring desk",
    associateNote: "Good substitute when blue formal shirting is low.",
    routeSteps: [
      "Enter through the main entrance on Ground Floor",
      "Take the escalator to Floor 2",
      "Turn right into Menswear",
      "Walk to Shirting",
      "Go to Aisle 10, Bay 3",
      "Associate can prepare Fitting Room 2",
    ],
  },
  {
    productId: "38974",
    storeId: "oak-street",
    floor: "Floor 2",
    department: "Menswear",
    zone: "Modern Formal",
    aisle: "Aisle 11",
    bay: "Bay 6",
    landmark: "black check rail under interview capsule signage",
    associateNote: "Use for smart-casual interview requests with black shoe substitutes.",
    routeSteps: [
      "Enter through the main entrance on Ground Floor",
      "Take the escalator to Floor 2",
      "Turn right into Menswear",
      "Walk into Modern Formal",
      "Go to Aisle 11, Bay 6",
      "Associate can prepare Fitting Room 2",
    ],
  },
  {
    productId: "48481",
    storeId: "oak-street",
    floor: "Floor 3",
    department: "Womenswear",
    zone: "Occasion Dresses",
    aisle: "Aisle 18",
    bay: "Bay 2",
    landmark: "black dress rail beside the mirrored styling table",
    associateNote: "Prioritise size 10 for work gala demand this week.",
    routeSteps: [
      "Enter through the main entrance on Ground Floor",
      "Take the escalator to Floor 3",
      "Turn left into Womenswear",
      "Walk to Occasion Dresses",
      "Go to Aisle 18, Bay 2",
      "Associate can prepare Fitting Room 5",
    ],
  },
  {
    productId: "59982",
    storeId: "oak-street",
    floor: "Floor 3",
    department: "Womenswear",
    zone: "Occasion Dresses",
    aisle: "Aisle 18",
    bay: "Bay 4",
    landmark: "cream-detail rail next to styling table",
    associateNote: "Keep beside black occasion dresses for gala substitutions.",
    routeSteps: [
      "Enter through the main entrance on Ground Floor",
      "Take the escalator to Floor 3",
      "Turn left into Womenswear",
      "Walk to Occasion Dresses",
      "Go to Aisle 18, Bay 4",
      "Associate can prepare Fitting Room 5",
    ],
  },
  {
    productId: "57993",
    storeId: "oak-street",
    floor: "Floor 3",
    department: "Womenswear",
    zone: "Occasion Dresses",
    aisle: "Aisle 17",
    bay: "Bay 3",
    landmark: "neutral event rail beside graduation edits",
    associateNote: "Works as a softer option for graduation and outdoor ceremonies.",
    routeSteps: [
      "Enter through the main entrance on Ground Floor",
      "Take the escalator to Floor 3",
      "Turn left into Womenswear",
      "Walk to Occasion Dresses",
      "Go to Aisle 17, Bay 3",
      "Associate can prepare Fitting Room 5",
    ],
  },
  {
    productId: "59973",
    storeId: "oak-street",
    floor: "Floor 3",
    department: "Womenswear",
    zone: "Occasion Dresses",
    aisle: "Aisle 18",
    bay: "Bay 1",
    landmark: "navy dress rail facing the escalator",
    associateNote: "Low depth; offer black dress substitute if size 12 is gone.",
    routeSteps: [
      "Enter through the main entrance on Ground Floor",
      "Take the escalator to Floor 3",
      "Turn left into Womenswear",
      "Walk to Occasion Dresses",
      "Go to Aisle 18, Bay 1",
      "Associate can prepare Fitting Room 5",
    ],
  },
  {
    productId: "34586",
    storeId: "oak-street",
    floor: "Floor 3",
    department: "Womenswear",
    zone: "Party Edit",
    aisle: "Aisle 19",
    bay: "Bay 2",
    landmark: "holiday-party rail near personal styling desk",
    associateNote: "Use for Friday holiday-party demand; pair with red heels.",
    routeSteps: [
      "Enter through the main entrance on Ground Floor",
      "Take the escalator to Floor 3",
      "Turn left into Womenswear",
      "Walk to Party Edit",
      "Go to Aisle 19, Bay 2",
      "Associate can prepare Fitting Room 6",
    ],
  },
  {
    productId: "47548",
    storeId: "oak-street",
    floor: "Floor 1",
    department: "Women's Shoes",
    zone: "Occasion Footwear",
    aisle: "Aisle 6",
    bay: "Bay 7",
    landmark: "red heel plinth opposite handbags fixture",
    associateNote: "Best accessory substitute for holiday-party outfits.",
    routeSteps: [
      "Enter through the main entrance on Ground Floor",
      "Walk to Floor 1 Women's Shoes",
      "Turn right into Occasion Footwear",
      "Go to Aisle 6",
      "Find Bay 7",
      "Associate can prepare Fitting Room 6",
    ],
  },
  {
    productId: "10616",
    storeId: "oak-street",
    floor: "Floor 1",
    department: "Women's Shoes",
    zone: "Occasion Footwear",
    aisle: "Aisle 6",
    bay: "Bay 4",
    landmark: "gold comfort footwear display under graduation signage",
    associateNote: "Comfort-first recommendation for ceremonies with long standing time.",
    routeSteps: [
      "Enter through the main entrance on Ground Floor",
      "Walk to Floor 1 Women's Shoes",
      "Turn right into Occasion Footwear",
      "Go to Aisle 6",
      "Find Bay 4",
      "Associate can prepare Fitting Room 6",
    ],
  },
  {
    productId: "32379",
    storeId: "oak-street",
    floor: "Floor 3",
    department: "Womenswear",
    zone: "Ceremony Edit",
    aisle: "Aisle 17",
    bay: "Bay 1",
    landmark: "light dress rail beside graduation capsule",
    associateNote: "Good ceremony option; call out that bag availability is limited.",
    routeSteps: [
      "Enter through the main entrance on Ground Floor",
      "Take the escalator to Floor 3",
      "Turn left into Womenswear",
      "Walk to Ceremony Edit",
      "Go to Aisle 17, Bay 1",
      "Associate can prepare Fitting Room 5",
    ],
  },
  {
    productId: "57139",
    storeId: "oak-street",
    floor: "Floor 3",
    department: "Womenswear",
    zone: "Workwear",
    aisle: "Aisle 15",
    bay: "Bay 5",
    landmark: "tailored trouser wall beside suiting capsule",
    associateNote: "Pair with black occasion dress rail for work gala separates.",
    routeSteps: [
      "Enter through the main entrance on Ground Floor",
      "Take the escalator to Floor 3",
      "Turn left into Womenswear",
      "Walk to Workwear",
      "Go to Aisle 15, Bay 5",
      "Associate can prepare Fitting Room 4",
    ],
  },
  {
    productId: "27917",
    storeId: "oak-street",
    floor: "Floor 3",
    department: "Womenswear",
    zone: "Workwear",
    aisle: "Aisle 15",
    bay: "Bay 3",
    landmark: "brown trouser rail near suiting capsule",
    associateNote: "Offer as work-event substitute when black trouser sizes are constrained.",
    routeSteps: [
      "Enter through the main entrance on Ground Floor",
      "Take the escalator to Floor 3",
      "Turn left into Womenswear",
      "Walk to Workwear",
      "Go to Aisle 15, Bay 3",
      "Associate can prepare Fitting Room 4",
    ],
  },
];
